export const Industries = [
  { value: "", key: "Select Industry" },
  { value: "Accounting&Finance", key: "Accounting, Auditing & Finance" },
  { value: "Admin&Office", key: "Admin & Office" },
  { value: "Building&Architecture", key: "Building & Architecture" },
  { value: "Community&SocialServices", key: "Community & Social Services" },
  { value: "Consulting&Strategy", key: "Consulting & Strategy" },
  { value: "Creative&Design", key: "Creative & Design" },
  { value: "CustomerService&Support", key: "Customer Service & Support" },
  { value: "Driver&TransportServices", key: "Driver & Transport Services" },
  { value: "Engineering&Technology", key: "Engineering & Technology" },
  {
    value: "EstateAgents&PropertyManagement",
    key: "Estate Agents & Property Management",
  },
  { value: "Farming&Agriculture", key: "Farming & Agriculture" },
  { value: "FoodServices&Catering", key: "Food Services & Catering" },
  { value: "Health&Safety", key: "Health & Safety" },
  { value: "Hospitality&Leisure", key: "Hospitality & Leisure" },
  { value: "HumanResources", key: "Human Resources" },
  { value: "LegalServices", key: "Legal Services" },
  {
    value: "Management&Business Development",
    key: "Management & Business Development",
  },
  { value: "Marketing&Communications", key: "Marketing & Communications" },
  { value: "Medical&Pharmaceutical", key: "Medical & Pharmaceutical" },
  { value: "Product&Project Management", key: "Product & Project Management" },
  { value: "QualityControl&Assurance", key: "Quality Control & Assurance" },
  { value: "ResearchTeaching&Training", key: "Research, Teaching & Training" },
  { value: "Sales", key: "Sales" },
  { value: "Software&Data", key: "Software & Data" },
  { value: "SupplyChain&Procurement", key: "Supply Chain & Procurement" },
  { value: "Trades&Services", key: "Trades & Services" },
  { value: "Other", key: "Other" },
];
